### ISSUE TITLE
"snarkyjs/no-greater-storage-limit-in-circuit" crashes

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/eslint-plugin-snarkyjs#10]
Crash experienced here: https://github.com/jackryanservia/mastermind
on this version of the source file: https://github.com/jackryanservia/mastermind/blob/2fdf3f6b7f8f09edf29a2c87c7f464c59782d629/src/Mastermind-recursive.ts

```
Oops! Something went wrong! :(

ESLint: 8.7.0

TypeError: Cannot read properties of undefined (reading 'size')
Occurred while linting /home/gregor/o1/mastermind/src/Mastermind-recursive.ts:37
Rule: "snarkyjs/no-greater-storage-limit-in-circuit"
    at Object.enter (/home/gregor/o1/mastermind/node_modules/eslint-plugin-snarkyjs/build/src/rules/no-greater-storage-limit-in-circuit.js:110:91)
    at SimpleTraverser.traverse (/home/gregor/o1/mastermind/node_modules/@typescript-eslint/typescript-estree/dist/simple-traverse.js:28:28)
    at SimpleTraverser.traverse (/home/gregor/o1/mastermind/node_modules/@typescript-eslint/typescript-estree/dist/simple-traverse.js:41:26)
    at SimpleTraverser.traverse (/home/gregor/o1/mastermind/node_modules/@typescript-eslint/typescript-estree/dist/simple-traverse.js:45:22)
    at simpleTraverse (/home/gregor/o1/mastermind/node_modules/@typescript-eslint/typescript-estree/dist/simple-traverse.js:51:53)
    at ClassDeclaration:has(Identifier[name="CircuitValue"]) (/home/gregor/o1/mastermind/node_modules/eslint-plugin-snarkyjs/build/src/rules/no-greater-storage-limit-in-circuit.js:101:56)
    at ruleErrorHandler (/home/gregor/o1/mastermind/node_modules/eslint/lib/linter/linter.js:1079:28)
    at /home/gregor/o1/mastermind/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/gregor/o1/mastermind/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
husky - pre-commit hook exited with code 1 (error)
```

**Comment by mitschabaude** [comment]
closed via #11
